apiVersion: v2
name: keycloak
description: Deploy Keycloak using Bitnami, wrapped as internal chart
type: application
version: 0.1.0
dependencies:
  - name: keycloak
    version: 24.0.3
    repository: https://charts.bitnami.com/bitnami
