keycloak:
  auth:
    adminUser: admin
    adminPassword: admin123

  production: false

  proxy: edge
  proxyAddressForwarding: true

  extraEnvVars:
    - name: KC_PROXY
      value: edge

  extraEnvVarsCM: ""  # Không dùng configmap ngoài

  service:
    type: ClusterIP
    ports:
      http: 8080

  ingress:
    enabled: false

  postgresql:
    enabled: true
    auth:
      username: bn_keycloak
      password: mysecretpass123
      database: bitnami_keycloak

  startupProbe:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 30
    timeoutSeconds: 5
    periodSeconds: 10

  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    failureThreshold: 15
    timeoutSeconds: 5
    periodSeconds: 10
