keycloak:
  auth:
    adminUser: admin
    adminPassword: admin123

  production: false
  proxyAddressForwarding: true

  extraEnvVarsCM: ""  # ← Fix lỗi nếu không có ConfigMap

  service:
    type: ClusterIP
    ports:
      http: 8080

  ingress:
    enabled: false

  startupProbe:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 30
    timeoutSeconds: 5
    periodSeconds: 10

  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    failureThreshold: 15
    timeoutSeconds: 5
    periodSeconds: 10
